FROM continuumio/miniconda3
RUN apt update && apt install build-essential -y && apt install git && apt install curl -y
WORKDIR /usr/
RUN git clone https://github.com/oobabooga/text-generation-webui
RUN mkdir /usr/models
RUN curl -L https:///huggingface.co/szymonrucinski/krakowiak-7b-gguf/resolve/main/krakowiak-7b.gguf.q4_k_m.bin -o /usr/models/krakowiak.gguf
WORKDIR /usr/text-generation-webui
RUN pip install -r requirements_nocuda.txt
RUN pip install llama-cpp-python
EXPOSE 7860
CMD python server.py --model-dir /usr/models --listen --listen-port 7860 --listen-host 0.0.0.0 
